//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lefarge_FE_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deficiency
    {
        public int Deficiencies_ID { get; set; }
        public string Deficiency1 { get; set; }
    }
}
