//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lefarge_FE_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int Equipment_ID { get; set; }
        public int Unit_Number { get; set; }
        public string Name { get; set; }
        public string Description1 { get; set; }
        public Nullable<int> Num_Of_Belts { get; set; }
        public string Belt_Type { get; set; }
        public int Plant_ID { get; set; }
        public int Category_ID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Plant Plant { get; set; }
    }
}
