//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lefarge_FE_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public Plant()
        {
            this.Equipments = new HashSet<Equipment>();
        }
    
        public int Plant_ID { get; set; }
        public string Plant_Name { get; set; }
        public string Address { get; set; }
        public string Phone_Num { get; set; }
        public string Postal_Code { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Equipment> Equipments { get; set; }
    }
}
